### ISSUE TITLE
generate random negative edges

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/N2V#2]
I think the generate random negative edges method does not generate completely "random" edges. IT.combination generates all combinations of edges, but I don't think how random are edges that we get.

**Comment by pnrobinson** [comment]
I do not think we want to have this method be a part of our package, since the correct "negative" edges are implementation dependent. Using IT.combination to generate all combinations of edges is very slow for large graphs. I do not think we should worry that much about this method and we can remove it from the code before we publish the package

**Comment by vidarmehr** [comment]
Oh, oK! I agree.
